
#配置Mysql相关
spring:
  data:
    mongodb:
      uri: mongodb://root:root@127.0.0.1:27017/zzh
  datasource:
    url: jdbc:mysql://121.37.136.40:3306/db2020?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: org.gjt.mm.mysql.Driver
    username: root
    password: zhz123...

    #Redis 配置
  redis:
    host: 121.37.136.40
    database: 0
    port: 6379
    password:
    jedis:
      pool:
        max-active: 20 # 连接池最大数量
        max-wait: 1
        max-idle: 10    # 连接池中最大空闲数
        min-idle: 0 #连接池中最小空闲数
    timeout: 1000     #连接超时时间





