
#配置Mysql相关
spring:
  datasource:
    url: jdbc:mysql://121.37.136.40:3306/db2020?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: org.gjt.mm.mysql.Driver
    username: root
    password: zhz123...



